name: alsallabi
description: ALSALLBI APP

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  audioplayers: ^2.0.0
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cached_pdfview: ^0.4.1
  flutter_html: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_localization: ^0.1.9
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hijri: ^3.0.0
  intl: any
  json_annotation: ^4.7.0
  lottie: ^2.2.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.7
  youtube_player_flutter: ^8.1.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "asset/icons/pet.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  freezed: any
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/telegram.png
    - assets/images/tiwter.png
    - assets/images/youtube.png
    - assets/images/logo-mob.jpg
    - assets/images/loading.svg
    - assets/images/123.jpg
    - assets/images/mp3.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: alsllabi_font
      fonts:
        - asset: assets/fonts/alsllabi_font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
